spring:
<<<<<<< HEAD
  security:
    oauth2:
      resourceserver:
        jwt:
          issues-uri: "http://localhost:9098/realms/micro-services"

=======
>>>>>>> 0d6a39da5b0e2e404ec94b747a2847beb51f0e09
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8222
