spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issues-uri: "http://localhost:9098/realms/micro-services"

  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8222
